services:
  nginx-dev:
    image: nginx:1.25-alpine
    container_name: transcendence_nginx_dev
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - transcendence_net
