/** Air / empty block. */
export const AIR = 0;

/** Bedrock — may only be placed by terrain generation, never by players/API. */
export const BEDROCK = 9;

/**
 * All valid block IDs, mirroring the frontend `Block` enum.
 * Blocks not in this set are rejected server-side.
 */
export const VALID_BLOCKS: ReadonlySet<number> = new Set([
  0,   // Air
  1,   // Stone
  2,   // Dirt
  3,   // Grass
  4,   // Wood
  5,   // Leaves
  6,   // Water
  7,   // Sand
  8,   // Glass
  9,   // Bedrock
  10,  // Pumpkin
  11,  // Furnace
  12,  // Plank
  13,  // AnvilBase
  14,  // BoneBlock
  15,  // Bookshelf
  16,  // BrewingStandBase
  17,  // Brick
  18,  // CauldronInner
  19,  // Clay
  20,  // CoalBlock
  21,  // CoalOre
  22,  // CoarseDirt
  23,  // Cobblestone
  24,  // CobblestoneMossy
  25,  // CommandBlock
  26,  // Comparator
  27,  // ConcreteBlack
  28,  // ConcreteBlue
  29,  // ConcreteBrown
  30,  // ConcreteCyan
  31,  // ConcreteGray
  32,  // ConcreteGreen
  33,  // ConcreteLightBlue
  34,  // ConcreteLime
  35,  // ConcreteMagenta
  36,  // ConcreteOrange
  37,  // ConcretePink
  38,  // ConcretePurple
  39,  // ConcreteRed
  40,  // ConcreteSilver
  41,  // ConcreteWhite
  42,  // ConcreteYellow
  43,  // CraftingTable
  44,  // DaylightDetector
  45,  // DaylightDetectorInverted
  46,  // DiamondBlock
  47,  // DiamondOre
  48,  // DirtPodzol
  49,  // DispenserFrontHorizontal
  50,  // DispenserFrontVertical
  51,  // DoorBirchLower
  52,  // DoorBirchUpper
  53,  // DoorDarkOakLower
  54,  // DoorDarkOakUpper
  55,  // DoorIronLower
  56,  // DoorSpruceLower
  57,  // DoorSpruceUpper
  58,  // DoorWoodLower
  59,  // DragonEgg
  60,  // DropperFrontHorizontal
  61,  // DropperFrontVertical
  62,  // EmeraldBlock
  63,  // EmeraldOre
  64,  // EndBricks
  65,  // EndStone
  66,  // FarmlandDry
  67,  // FarmlandWet
  68,  // FenceAcacia
  69,  // FenceAcaciaRail
  70,  // FenceBirch
  71,  // FenceBirchRail
  72,  // FenceDarkOak
  73,  // FenceDarkOakRail
  74,  // FenceJungle
  75,  // FenceJungleRail
  76,  // FenceNether
  77,  // FenceNetherRail
  78,  // FenceOak
  79,  // FenceOakRail
  80,  // FenceSpruce
  81,  // FenceSpruceRail
  82,  // FrostedIce0
  83,  // FrostedIce1
  84,  // FrostedIce2
  85,  // FrostedIce3
  86,  // GlassBlack
  87,  // GlassBlue
  88,  // GlassBrown
  89,  // GlassCyan
  90,  // GlassGray
  91,  // GlassGreen
  92,  // GlassLightBlue
  93,  // GlassLime
  94,  // GlassMagenta
  95,  // GlassOrange
  96,  // GlassPane
  97,  // GlassPaneTopBlack
  98,  // GlassPaneTopBlue
  99,  // GlassPaneTopBrown
  100, // GlassPaneTopCyan
  101, // GlassPaneTopGray
  102, // GlassPaneTopGreen
  103, // GlassPaneTopLightBlue
  104, // GlassPaneTopLime
  105, // GlassPaneTopMagenta
  106, // GlassPaneTopOrange
  107, // GlassPaneTopPink
  108, // GlassPaneTopPurple
  109, // GlassPaneTopRed
  110, // GlassPaneTopSilver
  111, // GlassPaneTopWhite
  112, // GlassPaneTopYellow
  113, // GlassPink
  114, // GlassPurple
  115, // GlassRed
  116, // GlassSilver
  117, // GlassWhite
  118, // GlassYellow
  119, // GlazedTerracottaLime
  120, // GlazedTerracottaWhite
  121, // Glowstone
  122, // GoldBlock
  123, // GoldOre
  124, // GrassSideSnowed
  125, // Gravel
  126, // HardenedClay
  127, // HardenedClayStainedBlack
  128, // HardenedClayStainedBlue
  129, // HardenedClayStainedBrown
  130, // HardenedClayStainedCyan
  131, // HardenedClayStainedGray
  132, // HardenedClayStainedGreen
  133, // HardenedClayStainedLightBlue
  134, // HardenedClayStainedLime
  135, // HardenedClayStainedMagenta
  136, // HardenedClayStainedOrange
  137, // HardenedClayStainedPink
  138, // HardenedClayStainedPurple
  139, // HardenedClayStainedRed
  140, // HardenedClayStainedSilver
  141, // HardenedClayStainedWhite
  142, // HardenedClayStainedYellow
  143, // HayBlock
  144, // HopperInside
  145, // HopperOutside
  146, // Ice
  147, // IcePacked
  148, // IronBlock
  149, // IronOre
  150, // IronTrapdoor
  151, // ItemframeBackground
  152, // Jukebox
  153, // LapisBlock
  154, // LapisOre
  155, // LavaFlow
  156, // LavaStill
  157, // LeavesAcaciaOpaque
  158, // LeavesBigOakOpaque
  159, // LeavesBirchOpaque
  160, // LeavesJungleOpaque
  161, // LeavesSpruceOpaque
  162, // LogAcacia
  163, // LogBigOak
  164, // LogBirch
  165, // LogJungle
  166, // LogSpruce
  167, // Magma
  168, // Melon
  169, // MushroomBlockInside
  170, // MushroomBlockSkinBrown
  171, // MushroomBlockSkinRed
  172, // MushroomBlockSkinStem
  173, // Mycelium
  174, // NetherBrick
  175, // NetherWartBlock
  176, // Netherrack
  177, // Noteblock
  178, // Obsidian
  179, // Piston
  180, // PistonInner
  181, // PistonTopNormal
  182, // PistonTopSticky
  183, // PlanksAcacia
  184, // PlanksBigOak
  185, // PlanksBirch
  186, // PlanksJungle
  187, // PlanksSpruce
  188, // PrismarineBricks
  189, // PrismarineDark
  190, // PrismarineRough
  191, // PumpkinFace
  192, // PurpurBlock
  193, // PurpurPillar
  194, // QuartzBlock
  195, // QuartzBlockChiseled
  196, // QuartzBlockLines
  197, // QuartzOre
  198, // RedNetherBrick
  199, // RedSand
  200, // RedSandstone
  201, // RedSandstoneCarved
  202, // RedSandstoneNormal
  203, // RedSandstoneSmooth
  204, // RedstoneBlock
  205, // RedstoneLamp
  206, // RedstoneOre
  207, // Repeater
  208, // Sandstone
  209, // SandstoneCarved
  210, // SandstoneNormal
  211, // SandstoneSmooth
  212, // SeaLantern
  213, // Slime
  214, // Snow
  215, // SoulSand
  216, // Sponge
  217, // SpongeWet
  218, // StoneAndesite
  219, // StoneAndesiteSmooth
  220, // StoneDiorite
  221, // StoneDioriteSmooth
  222, // StoneGranite
  223, // StoneGraniteSmooth
  224, // StoneSlab
  225, // Stonebrick
  226, // StonebrickCarved
  227, // StonebrickCracked
  228, // StonebrickMossy
  229, // Tnt
  230, // Trapdoor
  231, // TripWire
  232, // Unused
  233, // WaterFlow
  234, // WoolColoredBlack
  235, // WoolColoredBlue
  236, // WoolColoredBrown
  237, // WoolColoredCyan
  238, // WoolColoredGray
  239, // WoolColoredGreen
  240, // WoolColoredLightBlue
  241, // WoolColoredLime
  242, // WoolColoredMagenta
  243, // WoolColoredOrange
  244, // WoolColoredPink
  245, // WoolColoredPurple
  246, // WoolColoredRed
  247, // WoolColoredSilver
  248, // WoolColoredWhite
  249, // WoolColoredYellow
]);

/**
 * Blocks that make up the generated world (terrain + trees). They are free to
 * place. Every other block is "paid": placing it costs a campus coin and
 * breaking a placed one refunds a coin. Values mirror the frontend Block enum.
 */
export const FREE_BLOCKS: ReadonlySet<number> = new Set([
  1, // Stone
  2, // Dirt
  3, // Grass
  4, // Wood
  5, // Leaves
  6, // Water
  7, // Sand
  125, // Gravel
  208, // Sandstone
]);

/** A block whose placement/break affects the campus coin budget. */
export const isPaidBlock = (block: number): boolean =>
  block !== AIR && !FREE_BLOCKS.has(block);
